---
name: Build and push to Registry

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        uses: docker/metadata-action@v3
        with:
          images: |
            missioncriticalcloud/chef-workstation-cosmic
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
          tags: missioncriticalcloud/chef-workstation-cosmic:latest
